### ISSUE TITLE
How to update Query using update_object function?

### ISSUE THREAD

**Issue by Lucy95** [seb-angel/FuelSDK-Python-Wrapper#1]
what kind of values are to be passed to the parameters in the method (mentioned below) to update QueryText of a QueryDefinition object type.

1. object_id_dict
2. values_dict

 @validate_response()
    def update_object(self, object_type, object_id_dict=None, values_dict=None, data_extension_key=None, is_rest=False):
        obj = self.get_object_class(object_type, is_rest)
        if object_type in (ObjectType.DATA_EXTENSION_ROW, ObjectType.DATA_EXTENSION_COLUMN):
            obj.CustomerKey = data_extension_key
            obj.props = values_dict
        else:
            obj.props = object_id_dict
            obj.props.update(values_dict)
        return obj.patch()

**Comment by SnapLyte** [comment]
You can use it this way to update a Query Definition:
```python
res = api.update_object(ObjectType.QUERY_DEFINITION,
                        object_id_dict={"ObjectID": "12345xyz"},
                        values_dict={"QueryText": "SELECT t.field FROM Table AS t",
                                     "Name": "My Query New Name",
                                     "CustomerKey": "My_Query_Key",
                                     "CategoryID": 123,
                                     "TargetType": "DE",
                                     "TargetUpdateType": "Overwrite",
                                     "DataExtensionTarget": {
                                         "Name": "My Target DE",
                                         "CustomerKey": "My_Target_DE"
                                     }})
```

Only use the parts you want to change in values_dict but you need to have DataExtensionTarget to update the QueryText.
So you can reduce the call to only have:
```python
res = api.update_object(ObjectType.QUERY_DEFINITION,
                        object_id_dict={"ObjectID": "12345xyz"},
                        values_dict={"QueryText": "SELECT t.field FROM Table AS t",
                                     "DataExtensionTarget": {
                                         "Name": "My Target DE",
                                         "CustomerKey": "My_Target_DE"
                                     }})
```
